import type { FontPair } from "./types";

/**
 * Curated, local-only list of pairings.
 * No API usage; UI previews load via Google Fonts CDN.
 */
export const FONT_PAIRS: FontPair[] = [
  {
    id: "ui-inter-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "ui-inter-montserrat",
    titleFont: "Montserrat",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-ibmplexsans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-sourcesans3-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
  {
    id: "saas-worksans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "branding-playfair-inter",
    titleFont: "Playfair Display",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-fraunces-inter",
    titleFont: "Fraunces",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-dmserifdisplay-sourcesans3",
    titleFont: "DM Serif Display",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-bebasneue-inter",
    titleFont: "Bebas Neue",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-oswald-roboto",
    titleFont: "Oswald",
    bodyFont: "Roboto",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-montserrat-inter",
    titleFont: "Montserrat",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "marketing",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "luxury-playfair-sourceserif4",
    titleFont: "Playfair Display",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "luxury",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "luxury-dmserifdisplay-sourceserif4",
    titleFont: "DM Serif Display",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "luxury",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "editorial-fraunces-sourceserif4",
    titleFont: "Fraunces",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "editorial",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "editorial-playfair-sourcesans3",
    titleFont: "Playfair Display",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "editorial",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "ui-notosans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-notosans-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
  {
    id: "ui-inter-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
  },
  {
    id: "ui-sourcesans3-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "ui-ibmplexsans-dmsans",
    titleFont: "DM Sans",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
  },
  {
    id: "ui-worksans-montserrat",
    titleFont: "Montserrat",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "ui-roboto-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Roboto",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-inter-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
  {
    id: "saas-sourcesans3-montserrat",
    titleFont: "Montserrat",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-ibmplexsans-montserrat",
    titleFont: "Montserrat",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-dmsans-worksans",
    titleFont: "Work Sans",
    bodyFont: "DM Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
  {
    id: "branding-dmserifdisplay-inter",
    titleFont: "DM Serif Display",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-playfair-ibmplexsans",
    titleFont: "Playfair Display",
    bodyFont: "IBM Plex Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-fraunces-sourcesans3",
    titleFont: "Fraunces",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-playfair-worksans",
    titleFont: "Playfair Display",
    bodyFont: "Work Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "editorial-playfair-sourceserif4",
    titleFont: "Playfair Display",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "editorial",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "editorial-dmserifdisplay-sourceserif4",
    titleFont: "DM Serif Display",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "editorial",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "editorial-fraunces-inter",
    titleFont: "Fraunces",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "editorial",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-oswald-inter",
    titleFont: "Oswald",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-bebasneue-worksans",
    titleFont: "Bebas Neue",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-oswald-sourcesans3",
    titleFont: "Oswald",
    bodyFont: "Source Sans 3",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-bebasneue-ibmplexsans",
    titleFont: "Bebas Neue",
    bodyFont: "IBM Plex Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "luxury-playfair-inter",
    titleFont: "Playfair Display",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "luxury",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "luxury-fraunces-sourceserif4",
    titleFont: "Fraunces",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "luxury",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "ui-inter-spacegrotesk-low",
    titleFont: "Space Grotesk",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
  },
  {
    id: "ui-inter-montserrat-low",
    titleFont: "Montserrat",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
  },
  {
    id: "ui-roboto-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Roboto",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
  },
  {
    id: "ui-notosans-montserrat",
    titleFont: "Montserrat",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "ui-worksans-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
  },
  {
    id: "ui-sourcesans3-montserrat",
    titleFont: "Montserrat",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "ui-ibmplexsans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-inter-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-inter-montserrat",
    titleFont: "Montserrat",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-worksans-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
  {
    id: "saas-roboto-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Roboto",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-ibmplexsans-dmsans",
    titleFont: "DM Sans",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
  {
    id: "saas-notosans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "branding-playfair-roboto",
    titleFont: "Playfair Display",
    bodyFont: "Roboto",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-playfair-notosans",
    titleFont: "Playfair Display",
    bodyFont: "Noto Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-dmserifdisplay-roboto",
    titleFont: "DM Serif Display",
    bodyFont: "Roboto",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-fraunces-worksans",
    titleFont: "Fraunces",
    bodyFont: "Work Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "editorial-dmserifdisplay-sourcesans3",
    titleFont: "DM Serif Display",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "editorial",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "editorial-fraunces-sourcesans3",
    titleFont: "Fraunces",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "editorial",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "editorial-playfair-worksans",
    titleFont: "Playfair Display",
    bodyFont: "Work Sans",
    structure: "serif-sans",
    useCase: "editorial",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "luxury-dmserifdisplay-inter",
    titleFont: "DM Serif Display",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "luxury",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "luxury-playfair-ibmplexsans",
    titleFont: "Playfair Display",
    bodyFont: "IBM Plex Sans",
    structure: "serif-sans",
    useCase: "luxury",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "luxury-playfair-notosans",
    titleFont: "Playfair Display",
    bodyFont: "Noto Sans",
    structure: "serif-sans",
    useCase: "luxury",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "ui-spacegrotesk-lexend",
    titleFont: "Space Grotesk",
    bodyFont: "Lexend",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "dyslexic-friendly",
  },
  {
    id: "saas-dmsans-lexend",
    titleFont: "DM Sans",
    bodyFont: "Lexend",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
    theme: "professional",
    accessibility: "dyslexic-friendly",
  },
  {
    id: "ui-spacegrotesk-robotomono",
    titleFont: "Space Grotesk",
    bodyFont: "Roboto Mono",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "monospaced",
  },
  {
    id: "saas-dmsans-ibmplexmono",
    titleFont: "DM Sans",
    bodyFont: "IBM Plex Mono",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
    theme: "professional",
    accessibility: "monospaced",
  },
  {
    id: "ui-montserrat-lexend",
    titleFont: "Montserrat",
    bodyFont: "Lexend",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "friendly",
    accessibility: "dyslexic-friendly",
  },
  {
    id: "saas-spacegrotesk-lexend",
    titleFont: "Space Grotesk",
    bodyFont: "Lexend",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "dyslexic-friendly",
  },
  {
    id: "ui-dmsans-robotomono",
    titleFont: "DM Sans",
    bodyFont: "Roboto Mono",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "professional",
    accessibility: "monospaced",
  },
  {
    id: "saas-spacegrotesk-ibmplexmono",
    titleFont: "Space Grotesk",
    bodyFont: "IBM Plex Mono",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "monospaced",
  },
  {
    id: "branding-robotoslab-inter",
    titleFont: "Roboto Slab",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "medium",
    theme: "classic",
    accessibility: "none",
  },
  {
    id: "marketing-dancingscript-inter",
    titleFont: "Dancing Script",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-caveat-inter",
    titleFont: "Caveat",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-pacifico-inter",
    titleFont: "Pacifico",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-sacramento-worksans",
    titleFont: "Sacramento",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-satisfy-sourcesans3",
    titleFont: "Satisfy",
    bodyFont: "Source Sans 3",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-greatvibes-inter",
    titleFont: "Great Vibes",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-patrickhand-inter",
    titleFont: "Patrick Hand",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-indieflower-inter",
    titleFont: "Indie Flower",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-kalam-inter",
    titleFont: "Kalam",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-permanentmarker-inter",
    titleFont: "Permanent Marker",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-handlee-inter",
    titleFont: "Handlee",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-shadowsintolight-inter",
    titleFont: "Shadows Into Light",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "ui-spacegrotesk-worksans",
    titleFont: "Space Grotesk",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-spacegrotesk-sourcesans3",
    titleFont: "Space Grotesk",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-spacegrotesk-ibmplexsans",
    titleFont: "Space Grotesk",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-spacegrotesk-notosans",
    titleFont: "Space Grotesk",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-montserrat-worksans",
    titleFont: "Montserrat",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-montserrat-sourcesans3",
    titleFont: "Montserrat",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-montserrat-ibmplexsans",
    titleFont: "Montserrat",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-dmsans-worksans",
    titleFont: "DM Sans",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "friendly",
    accessibility: "none",
  },
  {
    id: "ui-dmsans-sourcesans3",
    titleFont: "DM Sans",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "friendly",
    accessibility: "none",
  },
  {
    id: "ui-dmsans-ibmplexsans",
    titleFont: "DM Sans",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "friendly",
    accessibility: "none",
  },
  {
    id: "ui-dmsans-notosans",
    titleFont: "DM Sans",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "friendly",
    accessibility: "none",
  },
  {
    id: "saas-spacegrotesk-worksans",
    titleFont: "Space Grotesk",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "saas-spacegrotesk-sourcesans3",
    titleFont: "Space Grotesk",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "saas-montserrat-notosans",
    titleFont: "Montserrat",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "saas-dmsans-ibmplexsans",
    titleFont: "DM Sans",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
    theme: "professional",
    accessibility: "none",
  },
  {
    id: "branding-playfair-sourcesans3",
    titleFont: "Playfair Display",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
    theme: "elegant",
    accessibility: "none",
  },
  {
    id: "branding-playfair-notosans",
    titleFont: "Playfair Display",
    bodyFont: "Noto Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
    theme: "elegant",
    accessibility: "none",
  },
  {
    id: "branding-playfair-worksans",
    titleFont: "Playfair Display",
    bodyFont: "Work Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
    theme: "elegant",
    accessibility: "none",
  },
  {
    id: "branding-dmserifdisplay-worksans",
    titleFont: "DM Serif Display",
    bodyFont: "Work Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
    theme: "formal",
    accessibility: "none",
  },
  {
    id: "branding-dmserifdisplay-notosans",
    titleFont: "DM Serif Display",
    bodyFont: "Noto Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
    theme: "formal",
    accessibility: "none",
  },
  {
    id: "branding-fraunces-ibmplexsans",
    titleFont: "Fraunces",
    bodyFont: "IBM Plex Sans",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
    theme: "classic",
    accessibility: "none",
  },
  {
    id: "editorial-fraunces-sourceserif4",
    titleFont: "Fraunces",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "editorial",
    readability: "medium",
    contrast: "medium",
    theme: "classic",
    accessibility: "long-form-text",
  },
  {
    id: "editorial-playfair-sourceserif4",
    titleFont: "Playfair Display",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "editorial",
    readability: "medium",
    contrast: "medium",
    theme: "classic",
    accessibility: "long-form-text",
  },
  {
    id: "marketing-dancingscript-worksans",
    titleFont: "Dancing Script",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-dancingscript-sourcesans3",
    titleFont: "Dancing Script",
    bodyFont: "Source Sans 3",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-caveat-worksans",
    titleFont: "Caveat",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-caveat-sourcesans3",
    titleFont: "Caveat",
    bodyFont: "Source Sans 3",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-pacifico-worksans",
    titleFont: "Pacifico",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-pacifico-sourcesans3",
    titleFont: "Pacifico",
    bodyFont: "Source Sans 3",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-satisfy-worksans",
    titleFont: "Satisfy",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-greatvibes-worksans",
    titleFont: "Great Vibes",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-indieflower-worksans",
    titleFont: "Indie Flower",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-kalam-worksans",
    titleFont: "Kalam",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-permanentmarker-worksans",
    titleFont: "Permanent Marker",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "marketing-patrickhand-worksans",
    titleFont: "Patrick Hand",
    bodyFont: "Work Sans",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
    theme: "playful",
    accessibility: "none",
  },
  {
    id: "ui-hankengrotesk-worksans",
    titleFont: "Hanken Grotesk",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "professional",
    accessibility: "none",
  },
  {
    id: "ui-hankengrotesk-sourcesans3",
    titleFont: "Hanken Grotesk",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "professional",
    accessibility: "none",
  },
  {
    id: "ui-hankengrotesk-ibmplexsans",
    titleFont: "Hanken Grotesk",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "professional",
    accessibility: "none",
  },
  {
    id: "ui-plusjakartasans-notosans",
    titleFont: "Plus Jakarta Sans",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-plusjakartasans-worksans",
    titleFont: "Plus Jakarta Sans",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-manrope-sourcesans3",
    titleFont: "Manrope",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-manrope-ibmplexsans",
    titleFont: "Manrope",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "low",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "saas-urbanist-worksans",
    titleFont: "Urbanist",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "saas-urbanist-sourcesans3",
    titleFont: "Urbanist",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "saas-sora-notosans",
    titleFont: "Sora",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "saas-sora-ibmplexsans",
    titleFont: "Sora",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "branding-outfit-worksans",
    titleFont: "Outfit",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "branding",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "branding-outfit-ibmplexsans",
    titleFont: "Outfit",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "branding",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
  {
    id: "ui-spacegrotesk-hankengrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Hanken Grotesk",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
    theme: "modern",
    accessibility: "none",
  },
];

