import type { FontPair } from "./types";

/**
 * Curated, local-only list of pairings.
 * No API usage; UI previews load via Google Fonts CDN.
 */
export const FONT_PAIRS: FontPair[] = [
  {
    id: "ui-inter-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "ui-inter-montserrat",
    titleFont: "Montserrat",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-ibmplexsans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "IBM Plex Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-sourcesans3-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Source Sans 3",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
  {
    id: "saas-worksans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Work Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "branding-playfair-inter",
    titleFont: "Playfair Display",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-fraunces-inter",
    titleFont: "Fraunces",
    bodyFont: "Inter",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "branding-dmserifdisplay-sourcesans3",
    titleFont: "DM Serif Display",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "branding",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-bebasneue-inter",
    titleFont: "Bebas Neue",
    bodyFont: "Inter",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-oswald-roboto",
    titleFont: "Oswald",
    bodyFont: "Roboto",
    structure: "display-sans",
    useCase: "marketing",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "marketing-montserrat-inter",
    titleFont: "Montserrat",
    bodyFont: "Inter",
    structure: "sans-sans",
    useCase: "marketing",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "luxury-playfair-sourceserif4",
    titleFont: "Playfair Display",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "luxury",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "luxury-dmserifdisplay-sourceserif4",
    titleFont: "DM Serif Display",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "luxury",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "editorial-fraunces-sourceserif4",
    titleFont: "Fraunces",
    bodyFont: "Source Serif 4",
    structure: "serif-serif",
    useCase: "editorial",
    readability: "medium",
    contrast: "medium",
  },
  {
    id: "editorial-playfair-sourcesans3",
    titleFont: "Playfair Display",
    bodyFont: "Source Sans 3",
    structure: "serif-sans",
    useCase: "editorial",
    readability: "medium",
    contrast: "high",
  },
  {
    id: "ui-notosans-spacegrotesk",
    titleFont: "Space Grotesk",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "ui",
    readability: "high",
    contrast: "medium",
  },
  {
    id: "saas-notosans-dmsans",
    titleFont: "DM Sans",
    bodyFont: "Noto Sans",
    structure: "sans-sans",
    useCase: "saas",
    readability: "high",
    contrast: "low",
  },
];

